### ISSUE TITLE
Allow overriding of attribute behavior

### ISSUE THREAD

**Issue by r4zzz4k** [Inkremental/anvil#27]
Right now to property support `id` for `ConstrantLayout` we had to resort to separate property called `constraintId`. Simple override of the method is not an option. Consider:
```
abstract class ViewScope {
	open fun id(...) = attr("id", ...)
}
abstract class ConstraintLayoutScope : ViewScope(...) {
	override fun id(...) = attr("constraintId", ...)
}
...
constraintLayout {
	textView {
		id(...)
	}
}
```
In this case we are actually calling `TextViewScope.id(...)`, which knows nothing about `ConstraintLayout`.
The only way to keep using `id` attribute is to allow setter derivatives to somehow override processing of attributes with the same name. `ConstraintDslSetter` should contribute it's own handling for `id`, which does the job only if `v.parent is ConstraintLayout`, otherwise passing it back to `SdkSetter`.

Additionally, collecting all setter code into corresponding collection would probably help with performance a bit as we'll have one search instead of a search per setter.

**Comment by sgrekov** [comment]
Maybe this can be partly solved by intercepting the call of AttributeSetter. 
For example if we can set the call priority of AttributeSetters, then setter of CL will intercept the call to "id" and will handle it in its own way. The question here is how to set this priority properly.

**Comment by sgrekov** [comment]
I will add another two cases, where this override will be very helpful.
1. Case that is described here
https://github.com/inkremental/inkremental/pull/66
Since we cannot override layoutGravity from core module in support modules, we now need to reinvent 
"new" attribute(coordinatorLayoutGravity) for the same purpose. 
2.  Case with setting compat values like here
https://github.com/inkremental/inkremental/pull/63/files
Since we want to "enhence" widgets from core module with support  classes, we have to manually put scope in call site. This also can be eliminated with override mechanism for Setters

**Comment by Mishkun** [comment]
Cant we dispatch some props based on the view class?

**Comment by r4zzz4k** [comment]
Sure, it's just the fact that, e.g., setter from sdk module matches `layoutGravity` property and takes any view, and coordinator's one would match `layoutGravity` only for `CoordinatorLayout` and derivatives. Problem here is the fact that first one, if registered earlier, would consume this. So we probably need not our current setters with huge `when`-s, but hashtable of view types + prop names to handlers for that specific properties.

**Comment by sgrekov** [comment]
Or maybe use SortedSet for storing AttributeSetter's as quick solution. And those AttributeSetters that need to override some behaviour will have higher sort attribute.

**Comment by r4zzz4k** [comment]
I'm fine with that if we agree that this is a temporary solution, as this obviously doesn't scale.
