### ISSUE TITLE
Consider more flexible versioning of support modules

### ISSUE THREAD

**Issue by sgrekov** [Inkremental/anvil#41]
At the moment versions of support modules are come bundled with main version of core module.
That means if we want to publish only one support module with new dependency version we need  bump version in the whole project. 
We need consider how to make it more flexible and do not break tooling with regards to semantic version.

**Comment by r4zzz4k** [comment]
So right now Gradle plugin already allows for multiple libraries within one Gradle project. Right now codegen to `src/main` is hard-written, so that's a first thing to fix.
We can do it iteratively:
1. Make code gen use separate source set so that we don't mix manual and generated code. This allows us to re-use manually written code for multiple libraries.
2. Add a concept of library version, which gets attached to project version for published artifacts.

At this point we should be able to have multiple versions of the same library with a bit of duplication in Gradle files.

3. Add something like version ranges, so that single library declaration can be re-used for multiple versions. This allows us to process much more library versions without too much manual work. For the latter, we should allow for more than one manual source set, so that we have enough flexibility with adapting for different gradual changes in libraries.

This is nice, but as a non-blocker can be postponed a bit.

I'll look what I can do with the first part.
